import Head from "next/head";
import { HeaderBanner, FooterBanner, Products } from "../components";
import { client } from "../libs/client";

export default function Home({ products, bannerData }) {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-[50px]">
        <HeaderBanner bannerData={bannerData[0]} />
        <Products productData={products}></Products>
        <FooterBanner bannerData={bannerData[0]} />
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const queryProducts = '*[_type == "product"]';
  const products = await client.fetch(queryProducts);
  const queryBanner = '*[_type == "banner"]';
  const bannerData = await client.fetch(queryBanner);
  return {
    props: { products, bannerData },
  };
};
