import Head from "next/head";
import Image from "next/image";
import { HeaderBanner, FooterBanner, Products } from "../components";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-[50px]">
        <HeaderBanner />
        <Products />
        <FooterBanner />
      </div>
    </div>
  );
}
